### ISSUE TITLE
Error detected 

### ISSUE THREAD

**Issue by sjprateek** [dhruvasagar/vim-zoom#12]
I get this below error only for the very first zoom attempt in vim. The zoom works too and I do not get errors when doing subsequent zoom toggles in the same vim session. Every new vim window with first zoom attempt shows this error.

Error detected while processing function zoom#toggle..<SNR>40_zoom_session_file:
line    3:
E216: No such group or event: TabClosed * call s:clean_session_file()

$ vim --version
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Apr 22 2013 10:02:34)
Compiled by wirobert@linux-rhel6-64

**Comment by dhruvasagar** [comment]
Thanks for reporting this, looks like the autocmd event `TabClosed` wasn't supported in 7.3, i've added a check for it now. Let me know if you face any issues after updating.

**Comment by sjprateek** [comment]
Works great after the update! thanks for the quick fix and this awesome plugin.
