### ISSUE TITLE
Can't see any status about zoom in lightline

### ISSUE THREAD

**Issue by thepenguinthatwants** [dhruvasagar/vim-zoom#13]
Hi!

I am using statusline and I added this to my vimrc

`let statusline+=%{zoom#statusline()}`

When I use zoom I cant see the notification on the lightline.

**Comment by dhruvasagar** [comment]
@thepenguinthatwants Hi, you'll have to refer to lightline's documentation on how to add segments to it's statusline.

**Comment by dhruvasagar** [comment]
https://github.com/itchyny/lightline.vim#advanced-configuration should help

**Comment by polyzen** [comment]
@thepenguinthatwants, you can see the first and last lines [highlighted here](https://gitlab.com/polyzen/dotfiles/blob/593f4a762fdaea4c65d5187c3fc15c71777705dd/base/.vim/vimrc#L115-141) as an example.
