### ISSUE TITLE
vim-zoom kills open NERDTree window

### ISSUE THREAD

**Issue by void-m4110c** [dhruvasagar/vim-zoom#15]
Hi, 

I have NERDTree open on the left and zoom into one of the splits right to it, then I exit the zoom and the content of the NERDTree sidebar is gone. I doesn't react to "NERDTreeToggle" or "NERDTreeClose" either. It looks like vim-zoom changes it's window type or so, because in order to close that (empty) window, I have to switch to it and close it with `:close`.

**Comment by dhruvasagar** [comment]
@void-m4110c This is a known limitation, since we're using vim sessions underneath, it's much more complex to support restoring such windows / buffers because they're designed to be discarded.
