### ISSUE TITLE
No effect

### ISSUE THREAD

**Issue by benlieb** [dhruvasagar/vim-zoom#16]
This seems like a cool plugin, but it doesn't do anything as far as I can tell. 

I tried the mapping (`C-Wm`) as well as `call zoom#toggle()` directly, and nothing changed. 

Am I missing something? The method above was found on auto complete, so install seems to have worked fine...

**Comment by benlieb** [comment]
I thought this would zoom text, but it maximizes the window. Ha. Ok, my bad.

**Comment by dhruvasagar** [comment]
@benlieb That's alright :), zooming text should mostly be outside the control of vim, `\<c-+>` does work in most terminal emulators and should also work within gui vim
