### ISSUE TITLE
NERDTree window is blank after it zoom and unzoom

### ISSUE THREAD

**Issue by assawalhy** [dhruvasagar/vim-zoom#19]
https://user-images.githubusercontent.com/42011920/129064384-56c86dee-12e9-4a9a-b5d9-7118e7dcc63d.mp4

**Comment by dhruvasagar** [comment]
@MuhammadSawalhy That is correct, this is a known limitation

**Comment by assawalhy** [comment]
I have just discovered this plugin, I will give it a try insha'Allah.

https://github.com/Pocco81/TrueZen.nvim

**Comment by SongTianxian9** [comment]
> @MuhammadSawalhy That is correct, this is a known limitation

maybe you can use :NERDTreeToggle to close the NERDTree before save session, and then use :NERDTreeToggle again after retrieval session. can this work it?

**Comment by dhruvasagar** [comment]
I have recently added `ZoomPre` and `ZoomPost` user autocmds, I would encourage you to use that for anything custom you may want to do before & after zoom.
