### ISSUE TITLE
Bug with zooming quickfix window

### ISSUE THREAD

**Issue by echuraev** [dhruvasagar/vim-zoom#2]
Hi,

I found a problem when I did search with Ack.
I have zoomed `qf` window and when I zoomed out, there is no search results in `qf` window.

Could you please fix it?

**Comment by dhruvasagar** [comment]
Hi,

I'll take a stab, although this actually is a bug with sessions.

**Comment by dhruvasagar** [comment]
I've pushed changes to preserve the quickfix list. However, it does not preserve the current selection index in the list, as of now it appears that it's not possible to preserve that. Let me know if face any issues. Thanks.
