### ISSUE TITLE
loosing window working dir

### ISSUE THREAD

**Issue by yazgoo** [dhruvasagar/vim-zoom#21]
Hi,

when i do a :tcd, zoom in and zoom out, then change window, :pwd is changed to the original directory.

**Comment by dhruvasagar** [comment]
@yazgoo I have pushed an update that should address this. Let me know if it's still an issue. This is on `vim` to get it right, but I believe with the right `sessionoptions` it should work.

**Comment by dhruvasagar** [comment]
Looks like this works on Neovim, but not on VIM

**Comment by yazgoo** [comment]
Thanks @dhruvasagar , it looks like it is indeed fixed on neovim !

**Comment by dhruvasagar** [comment]
@yazgoo I have pushed some updates let me know if you still face this issue.
