### ISSUE TITLE
zoom-out in tmux?

### ISSUE THREAD

**Issue by gcqmkm** [dhruvasagar/vim-zoom#22]
Why does zoom-out not work when in tmux?

**Comment by dhruvasagar** [comment]
@gcqmkm I use tmux actively, it works for me. Can you share in detail what and how you're trying to use vim-zoom ?

**Comment by gcqmkm** [comment]
Actually I was just stupid. It seems that it does not have anything to do with tmux. When zooming in function zoom#toggle I get an E474 error: sessionoptions+=blank,buffers,curdir,terminal,help
Most of the times zooming works, but sometimes, maybe with complex window structure 3windows vert split above and 1 window below, if i try to zoom in window below it freezes and zoom does not do anything. I need to press ctrl-c to make unfreeze vim, and then I can continue my work as normal. I use ctrl-w m. This problem seems not to appear when using ctrl-w z. It is kind of random.
I am using vim8.2

**Comment by dhruvasagar** [comment]
`vim-zoom` offers <kbd>\<C-w>m</kbd>, not <kbd>\<C-w>z</kbd>

**Comment by gcqmkm** [comment]
The error is caused by curdir parameter, since I have sesdir already in my sessionoptions by default.

**Comment by dhruvasagar** [comment]
@gcqmkm Interesting, thanks for that, let me try to address this.

**Comment by dhruvasagar** [comment]
@gcqmkm I've pushed an update that should address this. Let me know.

**Comment by gcqmkm** [comment]
Yes, actually I got the same error. I made a pull request with the code that works for me. Please check.

**Comment by dhruvasagar** [comment]
@gcqmkm But I have already fixed the issue.

**Comment by dhruvasagar** [comment]
@gcqmkm Is the fix I pushed not working for you ? Kindly let me know.

**Comment by gcqmkm** [comment]
It does not work for me. The code in pull request works.

**Comment by dhruvasagar** [comment]
@gcqmkm I haven't tried since my changes were solving it, i'll take another look.
