### ISSUE TITLE
Unzooming is very very long to process

### ISSUE THREAD

**Issue by dtrckd** [dhruvasagar/vim-zoom#23]
Meaning it takes about 5 second to unzoom...which feels like a eternity.

Any idea what it does and if there is opportunity to make it faster ?

IINFO: 
- I have 10 tab open, and something like 15 files....
- with just one file open and one split, its faster but stil its 2/3 second...
- version/commit used: 9f281ac

**Comment by dhruvasagar** [comment]
@dtrckd It shouldn't be tht slow, however, having large number of buffers open can slow vim down.

**Comment by dhruvasagar** [comment]
@dtrckd Hey, since I haven't heard from you or others regarding similar issues, I am going to close this issue for now. If you continue to face this issue consistently or others also report facing similar behavior, i'll reopen this and investigate again.
