### ISSUE TITLE
Zooming in and out causes open nvim-tree panes to be blank

### ISSUE THREAD

**Issue by armanschwarz** [dhruvasagar/vim-zoom#24]
I'm using neovim 0.7.2 with nvim-tree. If I zoom in and back out again from a code window in normal mode, any open nvim-tree window will appear blank, until I reopen nvim-tree and then it reappears.

The zooming out process is also a bit clunky, it takes about half a second and some text (it looks like some formatting, possibly from my init.vim file) flashes on the screen.

Great plugin otherwise, super useful. I hope this is helpful.

**Comment by dhruvasagar** [comment]
@armanschwarz This is a known limitation, vim-zoom does not restore special buffers like nvim-tree. These are custom buffers created by plugins.
