### ISSUE TITLE
Neovim: Zooming Out Makes Buffers One Line Tall

### ISSUE THREAD

**Issue by austinliuigi** [dhruvasagar/vim-zoom#26]
When I zoom out of a buffer that I previously zoomed in on, the buffers become one line in height

Before:
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/85013922/187012089-ace6ee63-e3c7-4b3b-b16c-7c678eeaa153.png">

After:
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/85013922/187012101-8205868a-f381-4ee7-bcf7-4f53c0b1ae2f.png">

**Comment by dhruvasagar** [comment]
@austinliuigi I am not able to reproduce this. Can you share a gif / screecast for better understanding ?

Also, in the before photo, I see you have 2 splits but a single statusline, which I find very weird, generally each window would have it's own statusline. ~Moreover, in the `after` screenshot you have just a single window, so I am assuming you're zooming in, not zooming out.~ I saw the split on the right later.

**Comment by austinliuigi** [comment]
Mysteriously, I just tried it again while trying to screencast it, but it seems to be working. I'll let you know if the issue pops up again.
