### ISSUE TITLE
Terminal output doesn't fill panel when zoom in

### ISSUE THREAD

**Issue by miguehm** [dhruvasagar/vim-zoom#28]
When zoom in my panel running a terminal with `:term`, the content does not fill the screen.
Add some screenshots

![Two panes](https://user-images.githubusercontent.com/80235345/201536505-31bb7312-2f57-4984-9103-d25bd5359961.png)

![Zoom in](https://user-images.githubusercontent.com/80235345/201536516-e59dcfc6-eff0-4fc7-bf87-240548535552.png)

**Comment by dhruvasagar** [comment]
@miguehm Based on the screenshot, it looks like the content was split into multiple lines, if it was soft wrapped instead, it would fill the space. This isn't related to vim-zoom.
