### ISSUE TITLE
lualine.nvim config

### ISSUE THREAD

**Issue by eggbean** [dhruvasagar/vim-zoom#29]
Just adding this here to save time for `lualine.nvim` users. This is my config to add the statusline notification:

```
-- Set lualine options
require('lualine').setup({
options = {
theme = 'Dracula',
section_separators = '', component_separators = '|',
},
sections = {
-- left
lualine_a = { 'mode' },
lualine_b = { 'branch', 'diff', 'diagnostic' },
lualine_c = { 'filename' },
-- right
lualine_x = { "vim.fn['zoom#statusline']()", 'encoding', 'fileformat', 'filetype' },
lualine_y = { 'progress' },
lualine_z = { 'location' }
},
extensions = { 'quickfix', 'fugitive', 'fzf' },
})
```

**Comment by dhruvasagar** [comment]
@eggbean Could you please create a PR and include that info within the README ?

**Comment by eggbean** [comment]
@dhruvasagar Yes, sure, but lualine only works with neovim and I think there are more popular statusline plugins, so wouldn't it be odd to have the config for lualine and not other more popular ones?

**Comment by dhruvasagar** [comment]
@eggbean something is better than nothing. I don't use statusline plugins so it would be better if it came from someone who is using it. Over time it can be extended and add info for others too.

**Comment by eggbean** [comment]
I made the PR. I've also been telling people about this plugin.

https://twitter.com/Max404s/status/1592181488984129536

Cheers!
