### ISSUE TITLE
ZoomWin

### ISSUE THREAD

**Issue by Konfekt** [dhruvasagar/vim-zoom#6]
Hello, just being curious: could you give hints how this compares to the good old ZoomWin by Dr. Chip, https://github.com/dr-chip-vim-scripts/ZoomWin ?

**Comment by dhruvasagar** [comment]
Hi,

I believe they are both similar in what they're trying to achieve, ZoomWin seems to have better support for temporary buffers. I believe vim-zoom source code is considerably concise for these reasons.

**Comment by polyzen** [comment]
Funny you ask as I'm trying to decide between this and https://github.com/troydm/zoomwintab.vim.

**Comment by Konfekt** [comment]
If I didn't use https://github.com/vim-ctrlspace/vim-ctrlspace/ that treats tabs as buffer containers, I'd find this to be the cleaner solution.

**Comment by bam80** [comment]
It's so many plugins doing the same thing..

**Comment by dhruvasagar** [comment]
That's the benefit of open source, you get alternates to use, with their own pros and cons, some of which may be better supported.
