### ISSUE TITLE
code be folded automatically

### ISSUE THREAD

**Issue by hzchirs** [dhruvasagar/vim-zoom#7]
Hi, when I open multiple windows, then zoom in and zoom out one of the windows, the code on all windows are folded automatically,
any ideas about this issue?
<img width="1680" alt="2019-02-19 9 37 23" src="https://user-images.githubusercontent.com/4735528/52984347-fe85dd00-3429-11e9-94dc-6cc7fc9b43d5.png">

**Comment by dhruvasagar** [comment]
It may be because of `foldlevel` setting, when the tab session is restored, it may get set again to whatever value was previous and so the folds may get folded accordingly, afaik there is no way to restore custom folded / unfolded state.

**Comment by hzchirs** [comment]
The root cause is `foldmethod=syntax`. Code will be folded when buffer open when the `foldmethod` is `syntax`
So I also set `foldlevel=20` to prevent this. But `vim-zoom` looks like not set the same `foldlevel` when session restored.

**Comment by dhruvasagar** [comment]
vim-zoom does not set any configs by itself, it creates a session using :mkssession and it restores the previous state by sourcing that file, all the options are recorded as they were while you zoom in and restored when zooming out. If you changed the foldlevel manually, or it got changed from some other plugin before you zoom in, it will be restored to that changed value when you zoom out.

**Comment by dhruvasagar** [comment]
Hi, I don't believe this is a issue with anything vim-zoom is doing, I am going to close this issue for now. If you need further help, lets discuss here and we can reopen in case there's something vim-zoom could do towards this.
