### ISSUE TITLE
Error processing zoom#toggle

### ISSUE THREAD

**Issue by gabrielBarbutti** [dhruvasagar/vim-zoom#9]
When I try to zoom in a window and there is changes in another file, occurs error E445 ("Other Window Contains Changes"). Variable zoomed is set to 1 anyway, this causes some strange behaviour like an adicional window with the same file opened.

Steps to reproduce:
- Open 2 files
- Change one
- Zoom in the unchaged file (Both files still appear)
- Zoom out with the cursor in the changed file

**Comment by dhruvasagar** [comment]
Thanks for reporting this issue, i'll have a look.

**Comment by dhruvasagar** [comment]
What error do you get ? In my case I am asked whether or not I want to save the changed file, then I can simply save it or say no. Zooming works as expected after that.

Also, if you `set hidden`, this also becomes a non-issue and zoom is able to zoom in as expected, on zooming out, you get back the unsaved buffer with your changes.

**Comment by gabrielBarbutti** [comment]
I got the following error
>Error detected while processing zoom#toggle:
>line 16:
>E445: Other Window Contains Changes
>Press enter or type command to continue

But when I `set hidden` it works fine, thank you
